# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6661c6dcde52bffece3cbd4577dce992fb99a310b2b67dfaff68041e96955590308edf6c9bb89dd10336d6e5e70f705879b50b55c6df280bcc719926bab0005e

test:
  secret_key_base: cebea5352d2f80be75591601705ff524f18e831fd5b938c2c43ea6e42f0df2497215b58dda1933ace2f5c8eeb9f1f52431fb81532f864ebe047a5f3dcf235a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
